fail_build to true
NijiDigital/forge-ios-niji pull request #17
Opened 2024-05-23 16:08 UTC by niji-mathieu-viel

2024-05-23 16:13 UTC, etilly commented on Forge.rb
> +    fail_build: true
Cela avait était par rapport à danger dans le cas ou danger est lancé après les TUs (scan de fastlane) pour que danger remonte les erreures de TU dans la MR.

2024-05-23 16:13 UTC, etilly approved these changes

2024-05-23 16:15 UTC, niji-mathieu-viel commented on Forge.rb
> +    fail_build: true
Ah oui ok! bon je patcherai ca quand j'intégrerai danger alors ;) parce que bon c pratique quand même si tu veux juste lancer les tests et que ta CI/CD fail si jamais les tests passent pas (sur azure devops genre)

2024-05-24 07:10 UTC, etilly commented on Forge.rb
> +    fail_build: true
Faut mettre une variable d'environnement à la place plus simple a gérer avec une valeur par défaut à true pour pas tous casser

2024-05-24 07:13 UTC, etilly requested changes

2024-05-24 07:13 UTC, etilly commented on Forge.rb
> +    fail_build: true
```ruby
fail_build: ENV.fetch('FAIL_BUILD', 'true') == 'true'
```

2024-05-24 07:14 UTC, etilly commented on Forge.rb
> +    fail_build: true
Voici les modifications apportées :

fail_build: ENV.fetch('FAIL_BUILD', 'true') == 'true' : On utilise ENV.fetch pour obtenir la valeur de l'environnement FAIL_BUILD. Si elle n'est pas définie, elle retourne 'true'. Ensuite, on compare cette valeur à la chaîne 'true' pour obtenir un booléen.

2024-05-24 07:16 UTC, etilly approved these changes

2024-05-24 07:16 UTC, niji-mathieu-viel commented on Forge.rb
> +    fail_build: true
C'est fait ;)

2024-05-24 07:17 UTC, merged